version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  flightsdb:
     image: mcr.microsoft.com/mssql/server:2019-latest
     ports:
     - 1433:1433
     environment:
       ACCEPT_EULA: Y
       MSSQL_SA_PASSWORD: RandomPassword123
       MSSQL_PID: EXPRESS

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
     - 27017:27017


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8079:8079
      - 808
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/




  flightsapi:
    image: ${DOCKER_REGISTRY-}flightsapi
    build:
      context: .
      dockerfile: Flights/Flights.Api/Dockerfile
    ports:
    - 8000:8000
    - 8004:8004



  flightsconsumerapi:
    image: ${DOCKER_REGISTRY-}flightsconsumerapi
    build:
      context: .
      dockerfile: FlightsExternalConsumer/FlightsConsumer.Api/Dockerfile
    ports:
    - 8001:8001
    - 8005:8005 

  # flightsui:
  #   image: ${DOCKER_REGISTRY-}flightsui
  #   build:
  #     context: .
  #     dockerfile: WebUI/FlightsUI/Dockerfile
  #   ports:
  #   - 8080:8080